kind: project
metadata:
  name: liveops-demo
  created: '2023-08-08T22:10:18.238000'
spec:
  functions:
  - url: src/project_setup.py
    name: image-builder
    kind: job
    image: mlrun/mlrun:1.3.3
    handler: assert_build
  - url: hub://describe
    name: describe
    kind: job
    handler: analyze
  - url: src/functions/train.py
    name: train
    kind: job
    image: mlrun/mlrun:1.3.3
    handler: train_model
  - url: src/functions/test_classifier.py
    name: test
    kind: job
    handler: test_classifier
  - url: hub://v2_model_server
    name: serving
    kind: serving
    image: mlrun/mlrun:1.3.3
    requirements: &id001
    - PyGithub==1.59.0
    - deepchecks==0.17.4
  - url: src/functions/simulate_traffic.py
    name: simulate-traffic
    kind: nuclio
    image: mlrun/mlrun:1.3.3
    requirements: *id001
  - url: src/functions/drift_watcher.py
    name: drift-watcher
    kind: nuclio
    image: mlrun/mlrun:1.3.3
    requirements: *id001
  - url: src/functions/create_drift_stream.py
    name: create-drift-stream
    kind: job
    handler: create_drift_stream
  - url: src/functions/fail_op.py
    name: fail
    kind: job
    handler: fail
  - url: src/functions/data.py
    name: data
    kind: job
  - url: src/functions/validate.py
    name: validate
    kind: job
  workflows:
  - path: src/workflows/train_and_deploy_workflow.py
    name: main
  artifacts: []
  conda: ''
  source: v3io:///bigdata/liveops.zip
  origin_url: git://github.com/igz-us-sales/igz-liveops-demo.git#refs/heads/master
  load_source_on_run: true
  desired_state: online
  owner: nick
  default_image: .mlrun/func-liveops-demo-image-builder:latest
status:
  state: online
